/*
	Author:	Richard Rulach
	Date:	18/04/2017
	Description:
*/

ALTER TABLE DPR_DW
ADD CONSTRAINT PK_DPR_DW_ID PRIMARY KEY CLUSTERED(DPR_DW_ID);
GO

ALTER TABLE PEPPER_DW
ADD CONSTRAINT PK_PEPPER_DW_ID PRIMARY KEY CLUSTERED(PEPPER_DW_ID);
GO




CREATE TABLE MAP_TABLE(
	MAP_TABLE_ID INT IDENTITY(1,1) NOT NULL,
	TABLE_NAME NVARCHAR(50) NOT NULL
);
GO

ALTER TABLE MAP_TABLE
ADD CONSTRAINT PK_MAP_TABLE PRIMARY KEY CLUSTERED(MAP_TABLE_ID);
GO

INSERT INTO MAP_TABLE(TABLE_NAME)
VALUES ('DPR_DW'),('PEPPER_DW');
GO



CREATE TABLE MAP__DPR_DW__PEPPER_DW(
	MAP__DPR_DW__PEPPER_DW__ID INT IDENTITY(1,1) NOT NULL,
	DPR_DW_ID INT NOT NULL,
	PEPPER_DW_ID INT NOT NULL
);
GO


ALTER TABLE MAP__DPR_DW__PEPPER_DW
ADD CONSTRAINT PK_MAP__DPR_DW__PEPPER_DW PRIMARY KEY CLUSTERED(MAP__DPR_DW__PEPPER_DW__ID);
GO

ALTER TABLE MAP__DPR_DW__PEPPER_DW
ADD CONSTRAINT FK_MAP__DPR_DW FOREIGN KEY(DPR_DW_ID)
	REFERENCES dbo.DPR_DW(DPR_DW_ID);
GO

ALTER TABLE MAP__DPR_DW__PEPPER_DW
ADD CONSTRAINT FK_MAP__PEPPER_DW FOREIGN KEY(PEPPER_DW_ID)
	REFERENCES dbo.PEPPER_DW(PEPPER_DW_ID);
GO




CREATE TABLE TAG(
	TAG_ID INT IDENTITY(1,1) NOT NULL,
	TAG_NAME NVARCHAR(50)
);

ALTER TABLE TAG
ADD CONSTRAINT PK_TAG PRIMARY KEY CLUSTERED(TAG_ID);
GO


CREATE TABLE MAP_TAG(
	TAG_ID		INT		NOT NULL,
	MAP_ID		INT		NOT NULL
);
GO

ALTER TABLE MAP_TAG
ADD CONSTRAINT FK_MAP_TAG__TAG FOREIGN KEY(TAG_ID)
	REFERENCES dbo.TAG(TAG_ID);
GO

ALTER TABLE MAP_TAG
ADD CONSTRAINT FK_MAP_TAG__MAP FOREIGN KEY(MAP_ID)
	REFERENCES dbo.MAP__DPR_DW__PEPPER_DW(MAP__DPR_DW__PEPPER_DW__ID);
GO



CREATE TABLE MAP__TAG__DPR_DW(
	TAG_ID		INT		NOT NULL,
	DPR_DW_ID	INT		NOT NULL
);
GO

ALTER TABLE MAP__TAG__DPR_DW
ADD CONSTRAINT FK__TAG__MAP__TAG__DPR_DW FOREIGN KEY(TAG_ID)
	REFERENCES dbo.TAG(TAG_ID);
GO

ALTER TABLE MAP__TAG__DPR_DW
ADD CONSTRAINT FK__TAG__MAP__DPR_DW FOREIGN KEY(DPR_DW_ID)
	REFERENCES dbo.DPR_DW(DPR_DW_ID);
GO





CREATE TABLE MAP__TAG__PEPPER_DW(
	TAG_ID			INT		NOT NULL,
	PEPPER_DW_ID	INT		NOT NULL
);
GO

ALTER TABLE MAP__TAG__PEPPER_DW
ADD CONSTRAINT FK__TAG__MAP__TAG FOREIGN KEY(TAG_ID)
	REFERENCES dbo.TAG(TAG_ID);
GO

ALTER TABLE MAP__TAG__PEPPER_DW
ADD CONSTRAINT FK__TAG__MAP__PEPPER_DW FOREIGN KEY(PEPPER_DW_ID)
	REFERENCES dbo.PEPPER_DW(PEPPER_DW_ID);
GO


-- FULL TEXT INDEXES
/*
CREATE FULLTEXT CATALOG TAG_CATALOG AS DEFAULT;
GO
CREATE FULLTEXT INDEX ON TAG(TAG_NAME)
	KEY INDEX PK_TAG
	ON TAG_CATALOG
	WITH STOPLIST = SYSTEM;
GO

*/


